language: python
python:
  - "3.6"
branches:
  only:
  - develop
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c "CREATE USER sekayasin WITH PASSWORD '';" -U postgres
  - psql -c 'create database fastfoodfast_test_db;' -U postgres
script:
  - py.test --cov=api tests/
  - coverage report -m
after_success:
  - coveralls
notifications:
  email: false
