language: python
python:
  - "3.6"
branches:
  only:
  - develop
install:
  - pip install -r requirements.txt
before_script:
- psql -c 'create database fastfoodfast_test_db;' -U sekayasin
script:
  - py.test --cov=api tests/
  - coverage report -m
after_success:
  - coveralls
notifications:
  email: false
